INSERT INTO public.exercises (user_id, exercise_name, exercise_type, exercise_category, is_active) VALUES
(NULL, '벤치 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '인클라인 벤치 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '디클라인 벤치 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '덤벨 벤치 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '인클라인 덤벨 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '디클라인 덤벨 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '스미스 머신 벤치 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '스미스 머신 인클라인 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '스미스 머신 디클라인 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '머신 체스트 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '인클라인 머신 체스트 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '디클라인 머신 체스트 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '케이블 체스트 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '원암 케이블 체스트 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '덤벨 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '인클라인 덤벨 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '디클라인 덤벨 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '케이블 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '하이 투 로우 케이블 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '로우 투 하이 케이블 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '펙덱 플라이', 'SYSTEM', 'CHEST', TRUE),
(NULL, '푸시업', 'SYSTEM', 'CHEST', TRUE),
(NULL, '인클라인 푸시업', 'SYSTEM', 'CHEST', TRUE),
(NULL, '디클라인 푸시업', 'SYSTEM', 'CHEST', TRUE),
(NULL, '웨이티드 푸시업', 'SYSTEM', 'CHEST', TRUE),
(NULL, '체스트 딥스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '어시스티드 체스트 딥스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '덤벨 풀오버', 'SYSTEM', 'CHEST', TRUE),
(NULL, '바벨 플로어 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '덤벨 플로어 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '길로틴 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '플레이트 스퀴즈 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '덤벨 헥스 프레스', 'SYSTEM', 'CHEST', TRUE),
(NULL, '컨벤셔널 데드리프트', 'SYSTEM', 'BACK', TRUE),
(NULL, '랙 풀', 'SYSTEM', 'BACK', TRUE),
(NULL, '풀업', 'SYSTEM', 'BACK', TRUE),
(NULL, '친업', 'SYSTEM', 'BACK', TRUE),
(NULL, '어시스티드 풀업', 'SYSTEM', 'BACK', TRUE),
(NULL, '와이드 그립 풀업', 'SYSTEM', 'BACK', TRUE),
(NULL, '뉴트럴 그립 풀업', 'SYSTEM', 'BACK', TRUE),
(NULL, '랫 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '와이드 그립 랫 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '클로즈 그립 랫 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '뉴트럴 그립 랫 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '원암 랫 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '스트레이트 암 풀다운', 'SYSTEM', 'BACK', TRUE),
(NULL, '바벨 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '펜들레이 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '티바 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '체스트 서포티드 티바 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '덤벨 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '원암 덤벨 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '체스트 서포티드 덤벨 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '시티드 케이블 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '와이드 그립 시티드 케이블 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '클로즈 그립 시티드 케이블 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '머신 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '해머 스트렝스 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '스미스 머신 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '인버티드 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '메도우 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '랜드마인 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '씰 로우', 'SYSTEM', 'BACK', TRUE),
(NULL, '백 익스텐션', 'SYSTEM', 'BACK', TRUE),
(NULL, '바벨 슈러그', 'SYSTEM', 'BACK', TRUE),
(NULL, '덤벨 슈러그', 'SYSTEM', 'BACK', TRUE),
(NULL, '백 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '프론트 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '하이바 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '로우바 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '스미스 머신 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '핵 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '펜듈럼 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '고블릿 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '벨트 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '레그 프레스', 'SYSTEM', 'LEGS', TRUE),
(NULL, '싱글 레그 프레스', 'SYSTEM', 'LEGS', TRUE),
(NULL, '레그 익스텐션', 'SYSTEM', 'LEGS', TRUE),
(NULL, '싱글 레그 익스텐션', 'SYSTEM', 'LEGS', TRUE),
(NULL, '불가리안 스플릿 스쿼트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '바벨 런지', 'SYSTEM', 'LEGS', TRUE),
(NULL, '덤벨 런지', 'SYSTEM', 'LEGS', TRUE),
(NULL, '워킹 런지', 'SYSTEM', 'LEGS', TRUE),
(NULL, '리버스 런지', 'SYSTEM', 'LEGS', TRUE),
(NULL, '스텝업', 'SYSTEM', 'LEGS', TRUE),
(NULL, '루마니안 데드리프트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '덤벨 루마니안 데드리프트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '스티프 레그 데드리프트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '굿모닝', 'SYSTEM', 'LEGS', TRUE),
(NULL, '라잉 레그 컬', 'SYSTEM', 'LEGS', TRUE),
(NULL, '시티드 레그 컬', 'SYSTEM', 'LEGS', TRUE),
(NULL, '스탠딩 레그 컬', 'SYSTEM', 'LEGS', TRUE),
(NULL, '노르딕 햄스트링 컬', 'SYSTEM', 'LEGS', TRUE),
(NULL, '힙 쓰러스트', 'SYSTEM', 'LEGS', TRUE),
(NULL, '글루트 브리지', 'SYSTEM', 'LEGS', TRUE),
(NULL, '케이블 풀스루', 'SYSTEM', 'LEGS', TRUE),
(NULL, '스탠딩 카프 레이즈', 'SYSTEM', 'LEGS', TRUE),
(NULL, '시티드 카프 레이즈', 'SYSTEM', 'LEGS', TRUE),
(NULL, '레그 프레스 카프 레이즈', 'SYSTEM', 'LEGS', TRUE),
(NULL, '오버헤드 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '시티드 바벨 숄더 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '덤벨 숄더 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '시티드 덤벨 숄더 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '아놀드 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '스미스 머신 숄더 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '머신 숄더 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '푸시 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '랜드마인 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '원암 랜드마인 프레스', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '덤벨 프론트 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '바벨 프론트 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '케이블 프론트 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '플레이트 프론트 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '덤벨 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '케이블 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '원암 케이블 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '머신 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '린어웨이 덤벨 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '인클라인 덤벨 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '바벨 업라이트 로우', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '케이블 업라이트 로우', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '덤벨 업라이트 로우', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '리버스 펙덱 플라이', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '리버스 덤벨 플라이', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '케이블 리어 델트 플라이', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '페이스 풀', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '리어 델트 로우', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '체스트 서포티드 리어 델트 로우', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '밴드 풀 어파트', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '덤벨 Y 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '케이블 Y 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '벤트오버 레터럴 레이즈', 'SYSTEM', 'SHOULDER', TRUE),
(NULL, '바벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, 'EZ바 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '덤벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '얼터네이팅 덤벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '해머 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '크로스 바디 해머 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '인클라인 덤벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '바벨 프리처 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, 'EZ바 프리처 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '덤벨 프리처 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '머신 프리처 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '케이블 바 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '로프 케이블 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '베이지안 케이블 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '원암 케이블 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '하이 케이블 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '스파이더 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '컨센트레이션 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '드래그 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '리버스 바벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '리버스 EZ바 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '리버스 덤벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '조트맨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '라잉 케이블 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '머신 바이셉스 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '플레이트 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '밴드 바이셉스 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '케틀벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '스트릭트 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '시티드 덤벨 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '바벨 21 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '인클라인 해머 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '프리처 해머 컬', 'SYSTEM', 'BICEPS', TRUE),
(NULL, '클로즈 그립 벤치 프레스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, 'JM 프레스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '벤치 딥스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '패러럴 바 딥스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '어시스티드 딥스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '클로즈 그립 푸시업', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '다이아몬드 푸시업', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '바 트라이셉스 푸시다운', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '로프 트라이셉스 푸시다운', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, 'V바 트라이셉스 푸시다운', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '리버스 그립 푸시다운', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '원암 케이블 푸시다운', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '크로스바디 케이블 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '오버헤드 로프 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '오버헤드 바 케이블 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '원암 오버헤드 케이블 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '투암 덤벨 오버헤드 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '원암 덤벨 오버헤드 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, 'EZ바 스컬 크러셔', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '바벨 라잉 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '인클라인 스컬 크러셔', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '덤벨 스컬 크러셔', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '테이트 프레스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '덤벨 킥백', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '케이블 킥백', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '머신 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '머신 딥스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '스미스 머신 클로즈 그립 벤치 프레스', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '스미스 머신 스컬 크러셔', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '바디웨이트 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, '라잉 케이블 트라이셉스 익스텐션', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, 'PJR 풀오버', 'SYSTEM', 'TRICEPS', TRUE),
(NULL, 'EZ바 프렌치 프레스', 'SYSTEM', 'TRICEPS', TRUE);