INSERT INTO exercise (name, body_part, user_id) VALUES
    ('벤치프레스', 'CHEST', NULL),
    ('인클라인 벤치프레스', 'CHEST', NULL),
    ('덤벨 벤치프레스', 'CHEST', NULL),
    ('체스트 프레스', 'CHEST', NULL),
    ('케이블 플라이', 'CHEST', NULL),
    ('랫풀다운', 'BACK', NULL),
    ('바벨 로우', 'BACK', NULL),
    ('시티드 케이블 로우', 'BACK', NULL),
    ('풀업', 'BACK', NULL),
    ('원암 덤벨 로우', 'BACK', NULL),
    ('숄더프레스', 'SHOULDERS', NULL),
    ('덤벨 숄더프레스', 'SHOULDERS', NULL),
    ('레터럴 레이즈', 'SHOULDERS', NULL),
    ('프론트 레이즈', 'SHOULDERS', NULL),
    ('리버스 펙덱', 'SHOULDERS', NULL),
    ('바벨 컬', 'ARMS', NULL),
    ('덤벨 컬', 'ARMS', NULL),
    ('해머 컬', 'ARMS', NULL),
    ('케이블 푸시다운', 'ARMS', NULL),
    ('스컬 크러셔', 'ARMS', NULL),
    ('스쿼트', 'LEGS', NULL),
    ('레그 프레스', 'LEGS', NULL),
    ('루마니안 데드리프트', 'LEGS', NULL),
    ('레그 익스텐션', 'LEGS', NULL),
    ('레그 컬', 'LEGS', NULL);
