spring.application.name=backend
spring.config.import=optional:file:.env.docker.local[.properties]

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/workout_log}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_ISSUER_URI:https://afiioqzrqmfuuzxruxke.supabase.co/auth/v1}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWKS_URI:https://afiioqzrqmfuuzxruxke.supabase.co/auth/v1/.well-known/jwks.json}
spring.security.oauth2.resourceserver.jwt.audiences[0]=${SUPABASE_JWT_AUDIENCE:authenticated}
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256
